# Site settings 配置站点
title: 'ELF的秘密基地-微博@SuperJunior1106_怦蓝心动打投组'
description: '微博@SuperJunior1106_怦蓝心动打投组，专注SuperJunior打投。感谢大眼仔给我们Github追星新体验。规则不断在变，一切以微博最新更新为准。'
keywords: 'SuperJunior1106_怦蓝心动打投组'
url: 'https://plxd1106.gitee.io' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  按标签: '/tags.html'
  按时间: '/timeline.html'
  关于我: '/about.html'
  相关下载: '/friendLink.html'

# 博主
author: true
name: ' ELF的秘密基地'
NickName: '微博@SuperJunior1106_怦蓝心动打投组'
webtitle: 'For ELF'
bio: '微博@SuperJunior1106_怦蓝心动打投组'
about: true
aboutyou: '最近大眼仔限流越来越频繁了，很多过去阅读量很大的教程都莫名其妙被设了权限，因此在这里对教程进行备份。感谢大眼仔给我们Github追星新体验。规则不断在变，一切请以微博的最新更新为准。如果能把这里放进收藏夹就更好啦~'
portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  #mail: 
  #weixin: '' # 你的微信二维码存放的地址
  #qq: '' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  github: 'http://plxd1106.github.io'
  #Codepen: ''
  weibo: 'https://weibo.com/u/7328949300'
  #instagram: ''
  #Twitter: ''
  #Dribbble: ''
  #Facebook: ''
  #Google: ''
  #zhihu: ''
  #juejin: ''
  #twitch: ''

# 分页
paginate: 2
paginatepath: ['page:num']

# since
footer:
  since: 2019.10.06

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 友情链接
friends:
  jekyll: 'https://plxd1106.github.io'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: false
disqus_url: '' # https://abc.disqus.com/embed.js

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'qzone']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: ''
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
