# Site settings 配置站点
title: 'ELF的秘密基地-微博@SuperJunior1106_怦蓝心动打投组'
description: '微博@SuperJunior1106_怦蓝心动打投组，专注SuperJunior打投。感谢大眼仔给我们Github追星新体验。规则不断在变，一切以微博最新更新为准。'
keywords: 'SuperJunior1106_怦蓝心动打投组'
url: 'plxd1106.gitee.io' # your host